// Generated by CoffeeScript 2.7.0
(function() {
  var AppView, InputView, Location, Locations, WeatherCardView, appView;

  Location = class Location extends Backbone.Model {
    parse(data) {
      return console.log(data);
    }

    getWeather() {
      var weatherJSONURL;
      weatherJSONURL = `https://api.openweathermap.org/data/2.5/weather?q=${this.attributes.cityName}&appid=7040d6303d83bfe36cc2fad1c5a7ae97&units=metric`;
      return $.ajax({
        method: "GET",
        url: weatherJSONURL,
        dataType: 'JSON'
      });
    }

  };

  Locations = (function() {
    class Locations extends Backbone.Collection {};

    Locations.prototype.model = Location;

    return Locations;

  }).call(this);

  WeatherCardView = (function() {
    class WeatherCardView extends Backbone.View {
      initialize() {
        return this.model.bind('change', this.render);
      }

      render() {
        var name, res, self;
        res = this.model.getWeather();
        name = this.model.get('cityName');
        self = this;
        res.then(function(data) {
          console.log(data);
          $(self.el).html(`<sl-card class="card-header m-4">
    <div slot="header" class="min-w-80 flex items-center justify-between">
        <h4>Weather in ${data.name}</h4>
        <sl-icon-button name="trash" label="Delete" class="delete-btn text-red-600"></sl-icon-button>
    </div>

    <p>Temperature: ${data.main.temp}°C</p>
    <p>Precipitaion: ${data.main.humidity}%</p>
</sl-card>`);
          return self;
        }).catch(function(err) {
          self.remove();
          alert("City not found " + name);
          return this;
        });
        $(this.el).append("<h4>Loading...</h4>");
        return this;
      }

      remove() {
        this.model.destroy();
        return $(this.el).remove();
      }

    };

    WeatherCardView.prototype.tagName = 'div';

    WeatherCardView.prototype.events = {
      'click .delete-btn': 'remove'
    };

    return WeatherCardView;

  }).call(this);

  InputView = (function() {
    class InputView extends Backbone.View {
      initialize() {
        return $(this.el).addClass("flex align-center items-center");
      }

      render() {
        $(this.el).html(`<sl-input id="city_name_input" placeholder="Enter city name" class="mr-4"></sl-input>
<sl-button id="add_btn">Add +</sl-button>`);
        return this;
      }

      addLocation() {
        var location, name;
        name = $("#city_name_input").val();
        if (!name) {
          return;
        }
        location = new Location();
        location.set('cityName', name);
        location.fetch({
          success: function() {
            return console.log(location.attributes);
          }
        });
        $("#city_name_input").val("");
        return this.model.add(location);
      }

    };

    InputView.prototype.tagName = "div";

    InputView.prototype.events = {
      'click #add_btn': 'addLocation'
    };

    return InputView;

  }).call(this);

  AppView = (function() {
    class AppView extends Backbone.View {
      initialize() {
        $(this.el).addClass("flex flex-col items-center p-4");
        this.locations = new Locations();
        this.locations.bind('add', this.appendItem);
        this.inputView = new InputView({
          model: this.locations
        });
        return this.render();
      }

      render() {
        $(this.el).append(this.inputView.render().el);
        return $(this.el).append("<div id='weather-cards' class='weather-cards m-8 flex flex-wrap'></div>");
      }

      appendItem(item) {
        var item_view;
        item_view = new WeatherCardView({
          model: item
        });
        return $("#weather-cards").append(item_view.render().el);
      }

    };

    AppView.prototype.el = $('#app');

    return AppView;

  }).call(this);

  Backbone.sync = function(method, model, success, error) {
    if (success.success) {
      return success.success();
    } else {
      console.log(method);
      return success();
    }
  };

  appView = new AppView();

}).call(this);
